create or replace PACKAGE PATH_IMG_FUNC IS

PROCEDURE INSERT_PATH_ALL(PA IN PATH_IMAGINI.PATH%TYPE, 
                            ALTT IN PATH_IMAGINI.ALT%TYPE, 
                            TIT IN PATH_IMAGINI.TITLE%TYPE,
                            COD_PROD IN PATH_IMAGINI.PRODUSE_COD_PRODUS%TYPE);

PROCEDURE UPDATE_PATH(PA IN PATH_IMAGINI.PATH%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE);

PROCEDURE UPDATE_ALT(ALTT IN PATH_IMAGINI.ALT%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE);

PROCEDURE UPDATE_TITLE(TIT IN PATH_IMAGINI.TITLE%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE);

PROCEDURE DELETE_ROW(ID_P IN PATH_IMAGINI.ID_PATH%TYPE);

END PATH_IMG_FUNC;
/

create or replace PACKAGE BODY PATH_IMG_FUNC IS

PROCEDURE INSERT_PATH_ALL(PA IN PATH_IMAGINI.PATH%TYPE, 
                            ALTT IN PATH_IMAGINI.ALT%TYPE, 
                            TIT IN PATH_IMAGINI.TITLE%TYPE,
                            COD_PROD IN PATH_IMAGINI.PRODUSE_COD_PRODUS%TYPE) IS
BEGIN
    INSERT INTO PATH_IMAGINI(PATH, ALT, TITLE, PRODUSE_COD_PRODUS) 
        VALUES(PA, ALTT, TIT, COD_PROD);
    commit;
END INSERT_PATH_ALL;

PROCEDURE UPDATE_PATH(PA IN PATH_IMAGINI.PATH%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE) IS
BEGIN
    UPDATE PATH_IMAGINI SET PATH = PA WHERE ID_PATH = ID_P;
END UPDATE_PATH;

PROCEDURE UPDATE_ALT(ALTT IN PATH_IMAGINI.ALT%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE) IS
BEGIN
    UPDATE PATH_IMAGINI SET ALT = ALTT WHERE ID_PATH = ID_P;
END UPDATE_ALT;

PROCEDURE UPDATE_TITLE(TIT IN PATH_IMAGINI.TITLE%TYPE, ID_P IN PATH_IMAGINI.ID_PATH%TYPE) IS
BEGIN
    UPDATE PATH_IMAGINI SET TITLE = TIT WHERE ID_PATH = ID_P;
END UPDATE_TITLE;

PROCEDURE DELETE_ROW(ID_P IN PATH_IMAGINI.ID_PATH%TYPE) IS
BEGIN
    DELETE FROM PATH_IMAGINI WHERE ID_PATH = ID_P; --STERGEM RANDUL
    --SELECT MAX(ID_COMANDA) INTO MAXIM FROM COMENZI_CURENTE; --AFLAM MAXIMUL 
    --ALTER TABLE COMENZI_CURENTE AUTO_INCREMENT := MAXIM +1; --RESETAM AUTOINCREMENTUL
END DELETE_ROW;

END PATH_IMG_FUNC;