-----------------------------------------------PACHET TABELA PRODUSE COMANDA----------------------------------------------------
CREATE OR REPLACE PACKAGE PROD_COM_FUNC IS

PROCEDURE INSERT_PRODUSE_COMANDA_ALL(PROD_COM IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE, 
                            NR_BUC IN PRODUSE_COMANDA.NR_BUCATI_COMANDATE%TYPE, 
                            ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE,
                            PRET_PR IN PRODUSE_COMANDA.PRET_PER_BUC%TYPE);

PROCEDURE UPDATE_COD_PRODUS(COD_PROD IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE);

PROCEDURE UPDATE_NR_BUCATI_COMANDATE(NR_BUC IN PRODUSE_COMANDA.NR_BUCATI_COMANDATE%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE);

PROCEDURE UPDATE_ID_COMANDA(ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE);

PROCEDURE DELETE_ROW_ID_COMANDA(ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE, COD_PROD IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE);

END PROD_COM_FUNC;
/

CREATE OR REPLACE PACKAGE BODY PROD_COM_FUNC IS

PROCEDURE INSERT_PRODUSE_COMANDA_ALL(PROD_COM IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE, 
                            NR_BUC IN PRODUSE_COMANDA.NR_BUCATI_COMANDATE%TYPE, 
                            ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE,
                            PRET_PR IN PRODUSE_COMANDA.PRET_PER_BUC%TYPE) IS
PRET_TTO PRODUSE_COMANDA.PRET_TOTAL%TYPE;
BEGIN
    PRET_TTO := NR_BUC * PRET_PR;
    INSERT INTO PRODUSE_COMANDA(COD_PRODUS_COMANDAT, NR_BUCATI_COMANDATE, COMENZI_CURENTE_ID_COMANDA, PRET_PER_BUC, PRET_TOTAL) 
        VALUES(PROD_COM, NR_BUC, ID_COM, PRET_PR, PRET_TTO);
END INSERT_PRODUSE_COMANDA_ALL;

PROCEDURE UPDATE_COD_PRODUS(COD_PROD IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE) IS
BEGIN
    UPDATE PRODUSE_COMANDA SET COD_PRODUS_COMANDAT = COD_PROD WHERE ID_PROD_COM = ID_P_C;
END UPDATE_COD_PRODUS;

PROCEDURE UPDATE_NR_BUCATI_COMANDATE(NR_BUC IN PRODUSE_COMANDA.NR_BUCATI_COMANDATE%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE) IS
BEGIN
    UPDATE PRODUSE_COMANDA SET NR_BUCATI_COMANDATE = NR_BUC WHERE ID_PROD_COM = ID_P_C;
END UPDATE_NR_BUCATI_COMANDATE;

PROCEDURE UPDATE_ID_COMANDA(ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE, ID_P_C IN PRODUSE_COMANDA.ID_PROD_COM%TYPE) IS
BEGIN
    UPDATE PRODUSE_COMANDA SET COMENZI_CURENTE_ID_COMANDA = ID_COM WHERE ID_PROD_COM = ID_P_C;
END UPDATE_ID_COMANDA;

PROCEDURE DELETE_ROW_ID_COMANDA(ID_COM IN PRODUSE_COMANDA.COMENZI_CURENTE_ID_COMANDA%TYPE, COD_PROD IN PRODUSE_COMANDA.COD_PRODUS_COMANDAT%TYPE) IS
BEGIN
    DELETE FROM PRODUSE_COMANDA WHERE COMENZI_CURENTE_ID_COMANDA = ID_COM AND COD_PRODUS_COMANDAT = COD_PROD; --STERGEM RANDUL
END DELETE_ROW_ID_COMANDA;

END PROD_COM_FUNC;
/
